name: Build and Release Tauri App

on:
  push:
    tags:
      - 'v*'  # ativa o workflow quando uma tag vX.Y.Z for criada

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: rust-chat
        run: npm install

      - name: Build Tauri app
        working-directory: rust-chat
        run: npx tauri build

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rust-chat/src-tauri/target/release/bundle/msi/*.msi
            rust-chat/src-tauri/target/release/bundle/nsis/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
