name: Build and Release Tauri App

on:
  push:
    tags:
      - 'v*'  # ativa o workflow quando uma tag vX.Y.Z for criada

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: rust-chat
        run: npm install

      - name: Build Tauri app
        working-directory: rust-chat
        run: npx tauri build

      - name: Upload MSI to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: rust-chat/src-tauri/target/release/bundle/msi/*.msi
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload NSIS to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: rust-chat/src-tauri/target/release/bundle/nsis/*.exe
          tag: ${{ github.ref }}
          file_glob: true
